[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install --production=false',
  'cd server && npm install --production=false',
  'cd client && npm install --production=false'
]

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'cd server && npm start'